app:
  port: 3002

database:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "Souny007"
  dbname: "demoDB"

minio:
  endpoint: "127.0.0.1:9000"
  accessKeyID: "QLzB65lbTp2EMwI7"
  secretAccessKey: "tksCIDTJ9aqbxK8LxkTkF4DidTzsfrMp"
  bucket: "dev-minio"
